name: translation_api
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.0.1
  meta: ^1.3.0
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^5.0.0
  test: ^1.17.0
  very_good_analysis: ^2.4.0