name: edamam_nutrition_api
description: A Flutter implementation of MealsApi that uses Edamam Nutrition Api
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  flutter:
    sdk: flutter
  http_service:
    path: ../../services/http_service
  ingredients_api:
    path: ../../interfaces/ingredients_api
  rxdart: ^0.27.2
  translator: ^0.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.2
  very_good_analysis: ^2.4.0
