name: ingredients_repository
description: A repository that handles ingredients related requests
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  ingredients_api:
    path: ../ingredients_api

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
